### ISSUE TITLE
Beaglebone black

### ISSUE THREAD

**Issue by GeethaAnd** [varghes/BeagleboneBlack-QNX-QT#2]
I tried the BSP, compiled and built in QNX6.5
IFS was copied to SD card and booted the beaglebone black.
But, BBB is continuously restarting.
Any inputs?

**Comment by varghes** [comment]
Hi , How you are flashing the SD Card ? what is the OS you are using ? MLO Uboot written correctly in the order ? did you try QNX official QNX image ?

**Comment by GeethaAnd** [comment]
Thanks for the response.
We have been using QNX in BBB with the BSP without the QT.  So, we have the
MLO & U-boot. This setup has been working well with the SD Cards.
Now I compiled the BSP as given by you and generated the ifs.bin with which
I replaced the older ifs.
With the newer BSP, BBB is restarting continuously.

**Comment by varghes** [comment]
can you post the serial console log ?
